### ISSUE TITLE
Error after Update to 10.0.41

### ISSUE THREAD

**Issue by JoPe72** [ameyer505/D365FOAdminToolkit#40] opened 2024-08-20 11:31 UTC
After updating our 10.0.40 environment with D365FO Admin Toolkit Installed to 10.0.41 I get the following error message when trying to add the System Administrator Role to a user:

Method not found: 'Dynamics.AX.Application.SysApplicationInsightsEventTelemetry Dynamics.AX.Application.SysApplicationInsightsEventTelemetry.addProperty(Dynamics.AX.Application.SysApplicationInsightsProperty)'.

The issue does not happen when I add another role. It does not help to add the user to excluded Users and it does not help to turn off Reason Message.

Since the message contained "Dynamics.AX.Application.SysApplicationInsightsEventTelemetry" I thought it might have something to do with @jofme s latest addition around logging so I tried disabling the telemetry... did not help... 

Does anyone have any idea?

**Comment by jofme** [comment] 2024-08-20 11:45
No idea. I'm still on 10.0.40, that's why I haven't seen the issue.
I just landed back in Denmark, but  I'll have a look at it later today.

**Comment by jofme** [comment] 2024-08-20 12:00
@JoPe72 there should be a parameter called "SysAdminLog" in the Admin Toolkit parameters. Have you tried disabling it?

**Comment by JoPe72** [comment] 2024-08-20 12:30
Yes I have... Does not solve it... That was my first thought when I saw SysApplicationInsightsEventTelemetry. I had just read your request/issue from the other day,

**Comment by ameyer505** [comment] 2024-08-20 13:58
@jofme @JoPe72 - Hey all, based on the error I agree that it looks like Microsoft has changed the method signatures on the SysApplicationInsightsEventTelemetry class in the 10.0.41 update

I am deploying an environment currently to take a look and will follow up with any findings

**Comment by JoPe72** [comment] 2024-08-20 14:50
Awesome... Let me know if I can help

**Comment by jofme** [comment] 2024-08-20 16:48
@JoPe72 @ameyer505  I managed to reproduce the issue in my OneBox machine after updating to the PEAP version in LCS's shared asset library.
<img width="289" alt="image" src="https://github.com/user-attachments/assets/2483456b-427b-4786-957f-8348b4c7f6d6">

To fix the issue, I simply had to rebuild the model. My going assumption is that there is some kind of binary incompatibility between the builds... Need to play with this a bit more.
@JoPe72 I can send you a deployable package build on 10.0.41 to test my theory?

**Comment by jofme** [comment] 2024-08-20 17:59
@ameyer505 you are correct, they have refactored SysApplicationInsightsEventTelemetry, so it now extends from SysApplicationInsightsTelemetryContractBase that contains the addProperty.
Updates should not break interfaces, and should always be backwards compatible; This is clearly a bug in the PEAP release.

I haven't gotten access to the Insider Yammer yet (Requested it a few months ago when I started at my new job). Can you check there for me?

The work-around is simple, I just move the check out of the method, so it never enters the method with the changed (and broken) interface. Then we at least can add admin roles, disregarding the telemetry. What do you say?

**Comment by ameyer505** [comment] 2024-08-20 18:14
@jofme thanks for confirming and appreciate the quick turnaround on this.

I am favor of the workaround and am happy to put out a 'hotfix' release once the new code is checked in.

I do not see anything within Yammer recently about either class you mentioned. I can go ahead a log a bug because I 100% agree with your assessment of 'updates to D365 should not break interfaces'.

**Comment by JoPe72** [comment] 2024-08-20 20:36
> @JoPe72 @ameyer505 I managed to reproduce the issue in my OneBox machine after updating to the PEAP version in LCS's shared asset library. <img alt="image" width="289" src="https://private-user-images.githubusercontent.com/96665013/359569114-2483456b-427b-4786-957f-8348b4c7f6d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxODYyNDEsIm5iZiI6MTcyNDE4NTk0MSwicGF0aCI6Ii85NjY2NTAxMy8zNTk1NjkxMTQtMjQ4MzQ1NmItNDI3Yi00Nzg2LTk1N2YtODM0OGI0YzdmNmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDIwMzIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMTVmZjkwMTIxMjc3OTgwNzA3NTQ4ZDExNjY2YzY2Mjk2Mzg0YTY3ZDc0NTEwZjdiYThkOTkyYjMwMWYzMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jMt1RgkgcKx9D1l51qSOAs5WCHGCy-fBGiduBi_wfYE">
> 
> To fix the issue, I simply had to rebuild the model. My going assumption is that there is some kind of binary incompatibility between the builds... Need to play with this a bit more. @JoPe72 I can send you a deployable package build on 10.0.41 to test my theory?

Yes Please :-)

**Closed as completed** 2024-08-20 21:04 UTC

**Comment by jofme** [comment] 2024-08-21 10:57
@JoPe72 here you go 😄

[D365AdminToolkit_1.7.0.0_10041.zip](https://github.com/user-attachments/files/16690498/D365AdminToolkit_1.7.0.0_10041.zip)

**Comment by JoPe72** [comment] 2024-08-21 15:22
Thanks @jofme, Great work. The fix worked perfectly!

**Comment by jofme** [comment] 2024-08-21 16:23
> Thanks @jofme, Great work. The fix worked perfectly!

Thanks @JoPe72 😄

And thats what's really weird...  It's the 1.7.0.0 release without changes, just built on a my machine with 10.0.41... 
Think I'll write a blog post this week about it.

Worst case is that ISV's will have to release every PU, and back port fixes to older PU...

**Comment by ameyer505** [comment] 2024-08-21 16:27
@jofme - whoa that is weird, would be really curious on the underlying root cause of this (irrespective of the impact to the toolkit but just for my knowledge as an ISV)

**Comment by Dynamicspedia** [comment] 2024-10-09 13:59
I got feedback today from a client testing the D365 Admin toolkit. They have the same error when removing the SysAdmin role from an user. I'm awaiting their Dynamics 365 version information. If they are on 10.0.41, then I will send the deployable package as shared above by @jofme to @JoPe72.

**Comment by ameyer505** [comment] 2024-10-09 18:43
@Dynamicspedia - I have created a new release that includes the changes for this bug

I have built the solution against a 10.0.39 and a 10.0.41 version of D365FO and have a release for each to hopefully support all current D365FO clients

https://github.com/ameyer505/D365FOAdminToolkit/releases/tag/v1.8

**Comment by headcase-fo** [comment] 2025-01-31 10:17
@ameyer505  @jofme 
Looks like the error is back. We have the toolkit v1.8 running in both, UATs and Prod. I wanted to give SysAdmin to a key user on a UAT. It also happens when I tried to revoke the SysAdmin from my account. 

The only difference is the build version: 
Prod: 10.0.41 (10.0.2015.78) -> no error
UAT: 10.0.41 (10.0.2015.145) -> error

The workaround for the UAT is to switch off the telemetry for the SysAdminLog.

**Comment by jofme** [comment] 2025-01-31 18:54
@headcase-fo It's interesting that this breaks in QU's.... I saw something similar in https://github.com/ITRasmus/FO_Integrations , But I haven't had time to investigate to further.

Thanks for the heads-up!
